# Generated by Django 5.2.10 on 2026-02-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
