# Generated by Django 5.2.10 on 2026-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_cancelled_qty_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NOT_INITIATED', 'Not Initiated'), ('INTIATED', 'Initiated'), ('COMPLETED', 'Completed')], default='NOT_INITIATED', max_length=20),
        ),
    ]
