# Generated by Django 5.2.10 on 2026-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_address_order_city_order_phone_order_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
