# Generated by Django 5.2.10 on 2026-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cash On Delivery')], default='ONLINE', max_length=20),
        ),
    ]
