# Generated by Django 5.2.10 on 2026-03-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], default='PLACED', max_length=20),
        ),
    ]
