# Generated by Django 5.2.10 on 2026-03-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NOT_INITIATED', 'Not Initiated'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed')], default='NOT_INITIATED', max_length=20),
        ),
    ]
