# Generated by Django 5.2.10 on 2026-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
